### ISSUE TITLE
No "Get Started" instructions

### ISSUE THREAD

**Issue by peterldowns** [mekarpeles/archive.org#9]
It's not obvious what dependencies are needed to run a local copy of the site, or how to do that. After cloning, I tried with the following:

``` shell
peterdowns@pld-air (12:48:48)
~/Desktop/Projects/archive.org ie-transform: python main.py 
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import waltz
ImportError: No module named waltz
peterdowns@pld-air (12:48:58)
~/Desktop/Projects/archive.org ie-transform:
```

It would be awesome if someone could add a `requirements.txt` file; I'd be happy to write the usage instructions after that. They'd look something like this:

```
pip install -r requirements.txt
python main.py
```

**Comment by mekarpeles** [comment]
Right now you can do the following to install all dependencies:

```
pip install -e .
```

This is also in the README. Feel free to add a requirements.txt as well
